export const WORDS = [
  "AGENT",
  "WORLD",
  "ABOUT",
  "HEART",
  "WATER",
  "SIXTY",
  "BOARD",
  "MONTH",
  "MUSIC",
  "PARTY",
  "PIANO",
  "MOUTH",
  "WOMAN",
  "SUGAR",
  "AMBER",
  "DREAM",
  "LAUGH",
  "TIGER",
  "EARTH",
  "MONEY",
  "WORDS",
  "SMILE",
  "LEMON",
  "SOUTH",
  "AFTER",
  "STONE",
  "THING",
  "LIGHT",
  "STORY",
  "POWER",
  "TODAY",
  "RANGE",
  "PEARL",
  "VENOM",
  "PROXY",
  "ROUND",
  "HOVER",
  "CANDY",
  "ABOVE",
  "PHONE",
  "OTHER",
  "SMART",
  "BLACK",
  "MAGIC",
  "FRUIT",
  "RADIO",
  "ROYAL",
  "HONEY",
  "FLAKE",
  "SOUND",
];

// A dictionary where the keys are the letters of the
//alphabet and the values are the status, a valid value
//for status is "not-pressed", "incorrect", "correct" or "misplaced"
export const KEYBOARD_DICT = {
  Q: "not-pressed",
  W: "not-pressed",
  E: "not-pressed",
  R: "not-pressed",
  T: "not-pressed",
  Y: "not-pressed",
  U: "not-pressed",
  I: "not-pressed",
  O: "not-pressed",
  P: "not-pressed",
  A: "not-pressed",
  S: "not-pressed",
  D: "not-pressed",
  F: "not-pressed",
  G: "not-pressed",
  H: "not-pressed",
  J: "not-pressed",
  K: "not-pressed",
  L: "not-pressed",
  Z: "not-pressed",
  X: "not-pressed",
  C: "not-pressed",
  V: "not-pressed",
  B: "not-pressed",
  N: "not-pressed",
  M: "not-pressed",
};
